services:
    mg-django:
        build:
            context: .
            dockerfile: docker/mg-django.dockerfile
        image: mg-django:latest  # ✅ Name your custom built image here
        container_name: 'mg-django'
        env_file:
            - .env
        networks:
            - mg-network
    mg-postgres:
        image: postgres:16
        restart: always
        env_file:
            - .env
        container_name: 'mg-postgres'
        volumes:
            - './postgres_data/:/var/lib/postgresql/data'
        networks:
            - mg-network
    mg-nginx:
        image: nginx:latest
        container_name: mg-nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - mg-network
        depends_on:
            - mg-django
networks:
    mg-network:
        name: mg-network
        external: true
