services:
    mg-django:
        image: python:3.10-bullseye
        env_file:
            - .env
        build:
            context: .
            dockerfile: docker/mg-django.dockerfile
        container_name: 'mg-django'
        # volumes: # in case specific dir should have live updates
        #    - './route/to/specific_dir/on/host:/app/specific_dir'
        depends_on:
            - mg-neo4j
        networks:
            - mg-network
    mg-neo4j:
        image: neo4j:5.11
        container_name: mg-neo4j
        environment:
            - NEO4J_AUTH=neo4j/neo4jpassword
        volumes:
            - "./neo4j_data/:/data"
        networks:
            - mg-network
    mg-postgres:
        image: postgres:16
        restart: always
        env_file:
            - .env
        container_name: 'mg-postgres'
        volumes:
            - './postgres_data/:/var/lib/postgresql/data'
        networks:
            - mg-network
    mg-nginx:
        image: nginx:latest
        container_name: mg-nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        networks:
            - mg-network
        depends_on:
            - mg-django
networks:
    mg-network:
        name: mg-network
        external: true
