# Generated by Django 5.0.4 on 2025-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
