# Generated by Django 5.0.4 on 2025-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Pending'), (3, 'Processing'), (4, 'Completed'), (5, 'Failed'), (6, 'Paused'), (7, 'Cancelled'), (8, 'Skipped'), (9, 'Timed Out')], default=2)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.JSONField(blank=True, null=True)),
                ('dataset', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks_extract_process',
            },
        ),
        migrations.CreateModel(
            name='MatchingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
            ],
            options={
                'verbose_name': 'Matching Report',
                'verbose_name_plural': 'Matching Reports',
            },
        ),
    ]
