# Generated by Django 5.0.4 on 2025-08-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('tasks', '0002_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.process')),
                ('graph', models.JSONField(blank=True, null=True)),
                ('dataset', models.JSONField(blank=True, null=True)),
            ],
            bases=('tasks.process',),
        ),
    ]
