# Generated by Django 5.0.4 on 2025-09-15 08:45

import importing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeClassificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.TextField(blank=True, default='None given', max_length=140, null=True)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Attribute Classification Report',
                'verbose_name_plural': 'Attribute Classification Reports',
            },
        ),
        migrations.CreateModel(
            name='FullTableCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=40000, unique=True)),
                ('validated_graph', models.BooleanField(default=False, verbose_name='Validated Graph')),
                ('graph', models.JSONField(null=True)),
            ],
            bases=(models.Model, importing.models.Cache),
        ),
        migrations.CreateModel(
            name='ImporterCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=200, unique=True)),
                ('column_label', models.CharField(blank=True, choices=[('Matter', 'Matter'), ('Property', 'Property'), ('Parameter', 'Parameter'), ('Measurement', 'Measurement'), ('Manufacturing', 'Manufacturing'), ('Metadata', 'Metadata'), ('No label', 'No label'), ('Simulation', 'Simulation'), (None, 'None')], max_length=200, null=True)),
                ('header_attribute', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('name', 'Name'), ('value', 'Value'), ('unit', 'Unit'), ('error', 'Error'), ('std', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('mean', 'Mean'), ('median', 'Median'), ('concentration', 'Concentration'), ('ratio', 'Ratio'), ('batch_number', 'Batch'), ('No attribute', 'No attribute'), (None, 'None')], max_length=200, null=True)),
                ('column_attribute', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('name', 'Name'), ('value', 'Value'), ('unit', 'Unit'), ('error', 'Error'), ('std', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('mean', 'Mean'), ('median', 'Median'), ('concentration', 'Concentration'), ('ratio', 'Ratio'), ('batch_number', 'Batch'), ('No attribute', 'No attribute'), (None, 'None')], max_length=200, null=True)),
                ('sample_column', models.CharField(max_length=200)),
                ('validated_column_label', models.BooleanField(default=False, verbose_name='Validated Col-label')),
                ('validated_column_attribute', models.BooleanField(default=False, verbose_name='Validated Col-attribute')),
                ('validated_header_attribute', models.BooleanField(default=False, verbose_name='Validated Header-attribute')),
            ],
            bases=(models.Model, importing.models.Cache),
        ),
        migrations.CreateModel(
            name='ImportProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Pending'), (3, 'Processing'), (4, 'Completed'), (5, 'Failed'), (6, 'Paused'), (7, 'Cancelled'), (8, 'Skipped'), (9, 'Timed Out')], default=2)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_id', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('labels', models.JSONField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('nodes', models.JSONField(blank=True, null=True)),
                ('graph', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks_import_process',
            },
        ),
        migrations.CreateModel(
            name='LabelClassificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.TextField(blank=True, default='None given', max_length=140, null=True)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Label Classification Report',
                'verbose_name_plural': 'Label Classification Reports',
            },
        ),
        migrations.CreateModel(
            name='NodeExtractionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.TextField(blank=True, default='None given', max_length=140, null=True)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Node Extraction Report',
                'verbose_name_plural': 'Node Extraction Reports',
            },
        ),
    ]
