# Generated by Django 5.0.4 on 2024-10-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0003_alter_importercache_column_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('labels', models.JSONField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
                ('graph', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(default='idle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
