# Generated by Django 5.0.4 on 2025-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0004_importprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprocess',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Pending'), (3, 'Processing'), (4, 'Completed'), (5, 'Failed'), (6, 'Paused'), (7, 'Cancelled'), (8, 'Skipped'), (9, 'Timed Out')], default=2),
        ),
    ]
