# Generated by Django 5.0.4 on 2025-08-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0006_link_importprocess_to_process'),
        ('tasks', '0002_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importprocess',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='importprocess',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='importprocess',
            name='process_id',
        ),
        migrations.RemoveField(
            model_name='importprocess',
            name='status',
        ),
        migrations.RemoveField(
            model_name='importprocess',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='importprocess',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='importprocess',
            name='process_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.process'),
        ),
    ]
