# Generated by Django 5.0.4 on 2024-08-31 23:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('opentrons', models.JSONField(blank=True, null=True)),
                ('labware', models.JSONField(blank=True, null=True)),
                ('chemicals', models.JSONField(blank=True, null=True)),
                ('biologic', models.JSONField(blank=True, null=True)),
                ('arduino', models.JSONField(blank=True, null=True)),
                ('arduino_relays', models.JSONField(blank=True, null=True)),
                ('workflow', models.JSONField()),
                ('status', models.CharField(choices=[('queued', 'QUEUED'), ('running', 'RUNNING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='queued')),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
