# Generated by Django 5.0.4 on 2024-09-29 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("opentrons", models.JSONField()),
                ("labware", models.JSONField()),
                ("chemicals", models.JSONField()),
                ("biologic", models.JSONField(blank=True, null=True)),
                ("arduino", models.JSONField(blank=True, null=True)),
                ("arduino_relays", models.JSONField(blank=True, null=True)),
                ("workflow", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "QUEUED"),
                            ("running", "RUNNING"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                        ],
                        default="queued",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("results", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
