# Generated by Django 5.0.4 on 2024-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(default={'chemicals': [], 'labware': []}),
        ),
    ]
